/*=============================================================================
Copyright (c) 2016 Paul W. Bible
Distributed under the Boost Software License, Version 1.0.
==============================================================================*/

#ifndef KGL_KOL_LIBRARY_H
#define KGL_KOL_LIBRARY

#include "Accumulators.h"
#include "kol_AllowedRelationshipOboGoParser.h"
#include "kol_AllowedRelationshipXmlGoParser.h"
#include "AllowedSetEvidencePolicy.h"
#include "AllowedSetRelationshipPolicy.h"
#include "AllPairsAverageSetSimilarity.h"
#include "AllPairsMaxSetSimilarity.h"
#include "kol_AncestorMeanSharedInformation.h"
#include "kol_AnnotationData.h"
#include "kol_AnnotationParserFactory.h"
#include "kol_AnnotationParserInterface.h"
#include "AppUtilities.h"
#include "BestMatchAverageSetSimilarity.h"
#include "kol_CoutoGraSMAdjustedSharedInformation.h"
#include "kol_CoutoGraSMSharedInformation.h"
#include "DisallowedSetEvidencePolicy.h"
#include "kol_enrichment_tools.h"
#include "kol_EntrezGene2GoAnnotationParser.h"
#include "EvidencePolicyInterface.h"
#include "kol_ExclusivelyInheritedSharedInformation.h"
#include "ExperimentalEvidencePolicy.h"
#include "kol_FrontierSharedInformation.h"
#include "kol_GentlemanSimUISetSimilarity.h"
#include "kol_GoaAnnotationParser.h"
#include "GoEnums.h"
#include "kol_GoGraph.h"
#include "kol_GoParserFactory.h"
#include "kol_GoParserInterface.h"
#include "JaccardSetSimilarity.h"
#include "kol_JiangConrathSimilarity.h"
#include "kol_LinSimilarity.h"
#include "kol_MazanduSimDICSetSimilarity.h"
#include "kol_MazanduSimUICSetSimilarity.h"
#include "kol_MgiAnnotationParser.h"
#include "kol_MICASharedInformation.h"
#include "ModularJiangConrath.h"
#include "ModularLin.h"
#include "ModularResnik.h"
#include "NCList.h"
#include "kol_PekarStaabSimilarity.h"
#include "kol_PesquitaSimGICSetSimilarity.h"
#include "PrecomputedMatrixTermSimilarity.h"
#include "kol_RapidXmlGoParser.h"
#include "RelationshipPolicyInterface.h"
#include "kol_RelevanceSimilarity.h"
#include "kol_ResnikSimilarity.h"
#include "SetUtilities.h"
#include "SharedInformationInterface.h"
#include "SimpleRegion.h"
#include "kol_StandardOboGoParser.h"
#include "StandardRelationshipPolicy.h"
#include "kol_StandardXmlGoParser.h"
#include "kol_TermDepthMap.h"
#include "kol_TermInformationContentMap.h"
#include "kol_TermProbabilityMap.h"
#include "TermSetSimilarityInterface.h"
#include "kol_TermSimilarityCache.h"
#include "TermSimilarityInterface.h"
#include "kol_TermSimilarityWriter.h"


#endif
