
#include "kgl_variant_factory_vcf_parse_info.h"

namespace kgl = kellerberrin::genome;

// The Info field definitions for the GRCh38.r3.0 series of VCF files (automatically generated).
const kgl::VCFInfoProcessMap kgl::GnomadInfo_3_0::gnomad_3_0_map_ =

{
{ "AC", { true, "Alternate allele count for samples", "Integer", "A" } } ,
{ "AN", { false, "Total number of alleles in samples", "Integer", "1" } } ,
{ "AF", { false, "Alternate allele frequency in samples", "Float", "A" } } ,
{ "non_par", { false, "", "Flag", "0" } } ,
{ "lcr", { false, "Variant falls within a low complexity region", "Flag", "0" } } ,
{ "variant_type", { false, "Variant type (snv, indel, multi-snv, multi-indel, or mixed)", "String", "1" } } ,
{ "n_alt_alleles", { false, "Total number of alternate alleles observed at variant locus", "Integer", "A" } } ,
{ "ReadPosRankSum", { false, "Z-score from Wilcoxon rank sum test of alternate vs. reference read position bias", "Float", "1" } } ,
{ "MQRankSum", { false, "Z-score from Wilcoxon rank sum test of alternate vs. reference read mapping qualities", "Float", "1" } } ,
{ "RAW_MQ", { false, "", "Float", "1" } } ,
{ "DP", { false, "Depth of informative coverage for each sample; reads with MQ", "Integer", "1" } } ,
{ "MQ_DP", { false, "", "Integer", "1" } } ,
{ "VarDP", { false, "", "Integer", "1" } } ,
{ "MQ", { false, "Root mean square of the mapping quality of reads across all samples", "Float", "1" } } ,
{ "QD", { false, "Variant call confidence normalized by depth of sample reads supporting a variant", "Float", "1" } } ,
{ "FS", { false, "Phred-scaled p-value of Fisher's exact test for strand bias", "Float", "1" } } ,
{ "SB", { false, "", "Integer", "4" } } ,
{ "InbreedingCoeff", { false, "Inbreeding coefficient as estimated from the genotype likelihoods per-sample when compared against the Hardy-Weinberg expectation", "Float", "1" } } ,
{ "AS_VQSLOD", { false, "Log-odds ratio of being a true variant versus being a false positive under the trained allele-specific VQSR Gaussian mixture model", "Float", "1" } } ,
{ "NEGATIVE_TRAIN_SITE", { false, "Variant was used to build the negative training set of low-quality variants for VQSR", "Flag", "0" } } ,
{ "POSITIVE_TRAIN_SITE", { false, "Variant was used to build the positive training set of high-quality variants for VQSR", "Flag", "0" } } ,
{ "culprit", { false, "Worst-performing annotation in the VQSR Gaussian mixture model", "String", "1" } } ,
{ "SOR", { false, "Strand bias estimated by the symmetric odds ratio test", "Float", "1" } } ,
{ "AC_asj_female", { false, "Alternate allele count for female samples of Ashkenazi Jewish ancestry", "Integer", "A" } } ,
{ "AN_asj_female", { false, "Total number of alleles in female samples of Ashkenazi Jewish ancestry", "Integer", "1" } } ,
{ "AF_asj_female", { false, "Alternate allele frequency in female samples of Ashkenazi Jewish ancestry", "Float", "A" } } ,
{ "nhomalt_asj_female", { false, "Count of homozygous individuals in female samples of Ashkenazi Jewish ancestry", "Integer", "A" } } ,
{ "AC_eas_female", { false, "Alternate allele count for female samples of East Asian ancestry", "Integer", "A" } } ,
{ "AN_eas_female", { false, "Total number of alleles in female samples of East Asian ancestry", "Integer", "1" } } ,
{ "AF_eas_female", { false, "Alternate allele frequency in female samples of East Asian ancestry", "Float", "A" } } ,
{ "nhomalt_eas_female", { false, "Count of homozygous individuals in female samples of East Asian ancestry", "Integer", "A" } } ,
{ "AC_afr_male", { false, "Alternate allele count for male samples of African-American/African ancestry", "Integer", "A" } } ,
{ "AN_afr_male", { false, "Total number of alleles in male samples of African-American/African ancestry", "Integer", "1" } } ,
{ "AF_afr_male", { false, "Alternate allele frequency in male samples of African-American/African ancestry", "Float", "A" } } ,
{ "nhomalt_afr_male", { false, "Count of homozygous individuals in male samples of African-American/African ancestry", "Integer", "A" } } ,
{ "AC_female", { false, "Alternate allele count for female samples", "Integer", "A" } } ,
{ "AN_female", { false, "Total number of alleles in female samples", "Integer", "1" } } ,
{ "AF_female", { false, "Alternate allele frequency in female samples", "Float", "A" } } ,
{ "nhomalt_female", { false, "Count of homozygous individuals in female samples", "Integer", "A" } } ,
{ "AC_fin_male", { false, "Alternate allele count for male samples of Finnish ancestry", "Integer", "A" } } ,
{ "AN_fin_male", { false, "Total number of alleles in male samples of Finnish ancestry", "Integer", "1" } } ,
{ "AF_fin_male", { false, "Alternate allele frequency in male samples of Finnish ancestry", "Float", "A" } } ,
{ "nhomalt_fin_male", { false, "Count of homozygous individuals in male samples of Finnish ancestry", "Integer", "A" } } ,
{ "AC_oth_female", { false, "Alternate allele count for female samples of Other ancestry", "Integer", "A" } } ,
{ "AN_oth_female", { false, "Total number of alleles in female samples of Other ancestry", "Integer", "1" } } ,
{ "AF_oth_female", { false, "Alternate allele frequency in female samples of Other ancestry", "Float", "A" } } ,
{ "nhomalt_oth_female", { false, "Count of homozygous individuals in female samples of Other ancestry", "Integer", "A" } } ,
{ "AC_ami", { false, "Alternate allele count for samples of Amish ancestry", "Integer", "A" } } ,
{ "AN_ami", { false, "Total number of alleles in samples of Amish ancestry", "Integer", "1" } } ,
{ "AF_ami", { false, "Alternate allele frequency in samples of Amish ancestry", "Float", "A" } } ,
{ "nhomalt_ami", { false, "Count of homozygous individuals in samples of Amish ancestry", "Integer", "A" } } ,
{ "AC_oth", { false, "Alternate allele count for samples of Other ancestry", "Integer", "A" } } ,
{ "AN_oth", { false, "Total number of alleles in samples of Other ancestry", "Integer", "1" } } ,
{ "AF_oth", { false, "Alternate allele frequency in samples of Other ancestry", "Float", "A" } } ,
{ "nhomalt_oth", { false, "Count of homozygous individuals in samples of Other ancestry", "Integer", "A" } } ,
{ "AC_male", { false, "Alternate allele count for male samples", "Integer", "A" } } ,
{ "AN_male", { false, "Total number of alleles in male samples", "Integer", "1" } } ,
{ "AF_male", { false, "Alternate allele frequency in male samples", "Float", "A" } } ,
{ "nhomalt_male", { false, "Count of homozygous individuals in male samples", "Integer", "A" } } ,
{ "AC_ami_female", { false, "Alternate allele count for female samples of Amish ancestry", "Integer", "A" } } ,
{ "AN_ami_female", { false, "Total number of alleles in female samples of Amish ancestry", "Integer", "1" } } ,
{ "AF_ami_female", { false, "Alternate allele frequency in female samples of Amish ancestry", "Float", "A" } } ,
{ "nhomalt_ami_female", { false, "Count of homozygous individuals in female samples of Amish ancestry", "Integer", "A" } } ,
{ "AC_afr", { false, "Alternate allele count for samples of African-American/African ancestry", "Integer", "A" } } ,
{ "AN_afr", { false, "Total number of alleles in samples of African-American/African ancestry", "Integer", "1" } } ,
{ "AF_afr", { false, "Alternate allele frequency in samples of African-American/African ancestry", "Float", "A" } } ,
{ "nhomalt_afr", { false, "Count of homozygous individuals in samples of African-American/African ancestry", "Integer", "A" } } ,
{ "AC_eas_male", { false, "Alternate allele count for male samples of East Asian ancestry", "Integer", "A" } } ,
{ "AN_eas_male", { false, "Total number of alleles in male samples of East Asian ancestry", "Integer", "1" } } ,
{ "AF_eas_male", { false, "Alternate allele frequency in male samples of East Asian ancestry", "Float", "A" } } ,
{ "nhomalt_eas_male", { false, "Count of homozygous individuals in male samples of East Asian ancestry", "Integer", "A" } } ,
{ "AC_sas", { false, "Alternate allele count for samples of South Asian ancestry", "Integer", "A" } } ,
{ "AN_sas", { false, "Total number of alleles in samples of South Asian ancestry", "Integer", "1" } } ,
{ "AF_sas", { false, "Alternate allele frequency in samples of South Asian ancestry", "Float", "A" } } ,
{ "nhomalt_sas", { false, "Count of homozygous individuals in samples of South Asian ancestry", "Integer", "A" } } ,
{ "AC_nfe_female", { false, "Alternate allele count for female samples of Non-Finnish European ancestry", "Integer", "A" } } ,
{ "AN_nfe_female", { false, "Total number of alleles in female samples of Non-Finnish European ancestry", "Integer", "1" } } ,
{ "AF_nfe_female", { false, "Alternate allele frequency in female samples of Non-Finnish European ancestry", "Float", "A" } } ,
{ "nhomalt_nfe_female", { false, "Count of homozygous individuals in female samples of Non-Finnish European ancestry", "Integer", "A" } } ,
{ "AC_asj_male", { false, "Alternate allele count for male samples of Ashkenazi Jewish ancestry", "Integer", "A" } } ,
{ "AN_asj_male", { false, "Total number of alleles in male samples of Ashkenazi Jewish ancestry", "Integer", "1" } } ,
{ "AF_asj_male", { false, "Alternate allele frequency in male samples of Ashkenazi Jewish ancestry", "Float", "A" } } ,
{ "nhomalt_asj_male", { false, "Count of homozygous individuals in male samples of Ashkenazi Jewish ancestry", "Integer", "A" } } ,
{ "AC_raw", { false, "Alternate allele count for samples, before removing low-confidence genotypes", "Integer", "A" } } ,
{ "AN_raw", { false, "Total number of alleles in samples, before removing low-confidence genotypes", "Integer", "1" } } ,
{ "AF_raw", { false, "Alternate allele frequency in samples, before removing low-confidence genotypes", "Float", "A" } } ,
{ "nhomalt_raw", { false, "Count of homozygous individuals in samples, before removing low-confidence genotypes", "Integer", "A" } } ,
{ "AC_oth_male", { false, "Alternate allele count for male samples of Other ancestry", "Integer", "A" } } ,
{ "AN_oth_male", { false, "Total number of alleles in male samples of Other ancestry", "Integer", "1" } } ,
{ "AF_oth_male", { false, "Alternate allele frequency in male samples of Other ancestry", "Float", "A" } } ,
{ "nhomalt_oth_male", { false, "Count of homozygous individuals in male samples of Other ancestry", "Integer", "A" } } ,
{ "AC_nfe_male", { false, "Alternate allele count for male samples of Non-Finnish European ancestry", "Integer", "A" } } ,
{ "AN_nfe_male", { false, "Total number of alleles in male samples of Non-Finnish European ancestry", "Integer", "1" } } ,
{ "AF_nfe_male", { false, "Alternate allele frequency in male samples of Non-Finnish European ancestry", "Float", "A" } } ,
{ "nhomalt_nfe_male", { false, "Count of homozygous individuals in male samples of Non-Finnish European ancestry", "Integer", "A" } } ,
{ "AC_asj", { false, "Alternate allele count for samples of Ashkenazi Jewish ancestry", "Integer", "A" } } ,
{ "AN_asj", { false, "Total number of alleles in samples of Ashkenazi Jewish ancestry", "Integer", "1" } } ,
{ "AF_asj", { false, "Alternate allele frequency in samples of Ashkenazi Jewish ancestry", "Float", "A" } } ,
{ "nhomalt_asj", { false, "Count of homozygous individuals in samples of Ashkenazi Jewish ancestry", "Integer", "A" } } ,
{ "AC_amr_male", { false, "Alternate allele count for male samples of Latino ancestry", "Integer", "A" } } ,
{ "AN_amr_male", { false, "Total number of alleles in male samples of Latino ancestry", "Integer", "1" } } ,
{ "AF_amr_male", { false, "Alternate allele frequency in male samples of Latino ancestry", "Float", "A" } } ,
{ "nhomalt_amr_male", { false, "Count of homozygous individuals in male samples of Latino ancestry", "Integer", "A" } } ,
{ "nhomalt", { false, "Count of homozygous individuals in samples", "Integer", "A" } } ,
{ "AC_amr_female", { false, "Alternate allele count for female samples of Latino ancestry", "Integer", "A" } } ,
{ "AN_amr_female", { false, "Total number of alleles in female samples of Latino ancestry", "Integer", "1" } } ,
{ "AF_amr_female", { false, "Alternate allele frequency in female samples of Latino ancestry", "Float", "A" } } ,
{ "nhomalt_amr_female", { false, "Count of homozygous individuals in female samples of Latino ancestry", "Integer", "A" } } ,
{ "AC_sas_female", { false, "Alternate allele count for female samples of South Asian ancestry", "Integer", "A" } } ,
{ "AN_sas_female", { false, "Total number of alleles in female samples of South Asian ancestry", "Integer", "1" } } ,
{ "AF_sas_female", { false, "Alternate allele frequency in female samples of South Asian ancestry", "Float", "A" } } ,
{ "nhomalt_sas_female", { false, "Count of homozygous individuals in female samples of South Asian ancestry", "Integer", "A" } } ,
{ "AC_fin", { false, "Alternate allele count for samples of Finnish ancestry", "Integer", "A" } } ,
{ "AN_fin", { false, "Total number of alleles in samples of Finnish ancestry", "Integer", "1" } } ,
{ "AF_fin", { false, "Alternate allele frequency in samples of Finnish ancestry", "Float", "A" } } ,
{ "nhomalt_fin", { false, "Count of homozygous individuals in samples of Finnish ancestry", "Integer", "A" } } ,
{ "AC_afr_female", { false, "Alternate allele count for female samples of African-American/African ancestry", "Integer", "A" } } ,
{ "AN_afr_female", { false, "Total number of alleles in female samples of African-American/African ancestry", "Integer", "1" } } ,
{ "AF_afr_female", { false, "Alternate allele frequency in female samples of African-American/African ancestry", "Float", "A" } } ,
{ "nhomalt_afr_female", { false, "Count of homozygous individuals in female samples of African-American/African ancestry", "Integer", "A" } } ,
{ "AC_sas_male", { false, "Alternate allele count for male samples of South Asian ancestry", "Integer", "A" } } ,
{ "AN_sas_male", { false, "Total number of alleles in male samples of South Asian ancestry", "Integer", "1" } } ,
{ "AF_sas_male", { false, "Alternate allele frequency in male samples of South Asian ancestry", "Float", "A" } } ,
{ "nhomalt_sas_male", { false, "Count of homozygous individuals in male samples of South Asian ancestry", "Integer", "A" } } ,
{ "AC_amr", { false, "Alternate allele count for samples of Latino ancestry", "Integer", "A" } } ,
{ "AN_amr", { false, "Total number of alleles in samples of Latino ancestry", "Integer", "1" } } ,
{ "AF_amr", { false, "Alternate allele frequency in samples of Latino ancestry", "Float", "A" } } ,
{ "nhomalt_amr", { false, "Count of homozygous individuals in samples of Latino ancestry", "Integer", "A" } } ,
{ "AC_nfe", { false, "Alternate allele count for samples of Non-Finnish European ancestry", "Integer", "A" } } ,
{ "AN_nfe", { false, "Total number of alleles in samples of Non-Finnish European ancestry", "Integer", "1" } } ,
{ "AF_nfe", { false, "Alternate allele frequency in samples of Non-Finnish European ancestry", "Float", "A" } } ,
{ "nhomalt_nfe", { false, "Count of homozygous individuals in samples of Non-Finnish European ancestry", "Integer", "A" } } ,
{ "AC_eas", { false, "Alternate allele count for samples of East Asian ancestry", "Integer", "A" } } ,
{ "AN_eas", { false, "Total number of alleles in samples of East Asian ancestry", "Integer", "1" } } ,
{ "AF_eas", { false, "Alternate allele frequency in samples of East Asian ancestry", "Float", "A" } } ,
{ "nhomalt_eas", { false, "Count of homozygous individuals in samples of East Asian ancestry", "Integer", "A" } } ,
{ "AC_ami_male", { false, "Alternate allele count for male samples of Amish ancestry", "Integer", "A" } } ,
{ "AN_ami_male", { false, "Total number of alleles in male samples of Amish ancestry", "Integer", "1" } } ,
{ "AF_ami_male", { false, "Alternate allele frequency in male samples of Amish ancestry", "Float", "A" } } ,
{ "nhomalt_ami_male", { false, "Count of homozygous individuals in male samples of Amish ancestry", "Integer", "A" } } ,
{ "AC_fin_female", { false, "Alternate allele count for female samples of Finnish ancestry", "Integer", "A" } } ,
{ "AN_fin_female", { false, "Total number of alleles in female samples of Finnish ancestry", "Integer", "1" } } ,
{ "AF_fin_female", { false, "Alternate allele frequency in female samples of Finnish ancestry", "Float", "A" } } ,
{ "nhomalt_fin_female", { false, "Count of homozygous individuals in female samples of Finnish ancestry", "Integer", "A" } } ,
{ "faf95_afr", { false, "Filtering allele frequency (using Poisson 95% CI) for samples of African-American/African ancestry", "Float", "A" } } ,
{ "faf99_afr", { false, "Filtering allele frequency (using Poisson 99% CI) for samples of African-American/African ancestry", "Float", "A" } } ,
{ "faf95_sas", { false, "Filtering allele frequency (using Poisson 95% CI) for samples of South Asian ancestry", "Float", "A" } } ,
{ "faf99_sas", { false, "Filtering allele frequency (using Poisson 99% CI) for samples of South Asian ancestry", "Float", "A" } } ,
{ "faf95_adj", { false, "", "Float", "1" } } ,
{ "faf99_adj", { false, "", "Float", "1" } } ,
{ "faf95_amr", { false, "Filtering allele frequency (using Poisson 95% CI) for samples of Latino ancestry", "Float", "A" } } ,
{ "faf99_amr", { false, "Filtering allele frequency (using Poisson 99% CI) for samples of Latino ancestry", "Float", "A" } } ,
{ "faf95_nfe", { false, "Filtering allele frequency (using Poisson 95% CI) for samples of Non-Finnish European ancestry", "Float", "A" } } ,
{ "faf99_nfe", { false, "Filtering allele frequency (using Poisson 99% CI) for samples of Non-Finnish European ancestry", "Float", "A" } } ,
{ "faf95_eas", { false, "Filtering allele frequency (using Poisson 95% CI) for samples of East Asian ancestry", "Float", "A" } } ,
{ "faf99_eas", { false, "Filtering allele frequency (using Poisson 99% CI) for samples of East Asian ancestry", "Float", "A" } } ,
{ "vep", { false, "Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|", "String", "." } } ,

};

