//
// Created by kellerberrin on 16/5/20.
//

#ifndef KGL_VARIANT_FACTORY_VCF_EVIDENCE_H
#define KGL_VARIANT_FACTORY_VCF_EVIDENCE_H


#include "kel_exec_env.h"
#include "kgl_variant_factory_vcf_parse_header.h"

#include <string>
#include <array>


namespace kellerberrin::genome {   //  organization level namespace




///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// A single evidence index, used to lookup an info field in a variant.
// The same index object can be used to look up data in all variants generated by a particular.
class InfoEvidenceHeader; // Fwd.
// The data type.
enum class InfoEvidenceType {
  Float,
  Integer,
  String,
  Boolean,
  FloatArray,
  IntegerArray,
  StringArray,
  IntegerAlternateAllele,
  FloatAlternateAllele,
  StringAlternateAllele,
  BooleanAlternateAllele,
  IntegerAllAllele,
  FloatAllAllele,
  StringAllAllele,
  BooleanAllAllele,
  IntegerGenotype,
  FloatGenotype,
  StringGenotype,
  BooleanGenotype,
  NotImplemented
};


// Defines the applicability of the data.
enum class InfoEvidenceApp {
  Scalar,   // General single valued data.
  Array,    // General array valued data
  AlternateAllele,  // Applies to the Alternate Alleles. Can be a single value for all alt. alleles or a vector of values for each alt. allele.
  AllAllele, // Applies to all Alleles including the reference allele. Can be a single value for all alleles or a vector of values for each allele.
  Genotype,  // Applies to all defined genotypes in the VCF file (if any). Can be a single value or a vector of values for each genotype.
};

// Defines how the data is represented.
enum class InfoEvidenceImpl {
  Boolean,
  Integer,
  Float,
  String,
  IntegerArray,
  StringArray,
  FloatArray
};


class InfoEvidenceIndex {

public:

  InfoEvidenceIndex(VCFInfoRecord vcfInfoRecord,
                    InfoEvidenceType type,
                    size_t index,
                    std::shared_ptr<const InfoEvidenceHeader> info_evidence_header)
  : vcfInfoRecord_(std::move(vcfInfoRecord)),
    type_(type),
    index_(index),
    info_evidence_header_(std::move(info_evidence_header)) {}

  InfoEvidenceIndex(const InfoEvidenceIndex &) = default; // Can be copied but not created externally.
  ~InfoEvidenceIndex() = default;

  [[nodiscard]] const VCFInfoRecord &infoRecord() const { return vcfInfoRecord_; }

  [[nodiscard]] InfoEvidenceType evidenceType() const { return type_; }

private:

  const VCFInfoRecord vcfInfoRecord_;
  const InfoEvidenceType type_;
  const size_t index_;
  std::shared_ptr<const InfoEvidenceHeader> info_evidence_header_; // Ensure the index knows which header it belongs to.

};

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// The index structure for the INFO evidence. This structure is held in common via shared_ptrs by all variants that
// subscribed to a particular set of INFO fields.
using InfoIndexMap = std::map<std::string, InfoEvidenceIndex>;

class InfoTypeCount {

public:

  InfoTypeCount() { reset(); }

  ~InfoTypeCount() = default;

  size_t floatCount() const { return float_count_; }

  size_t integerCount() const { return integer_count_; }

  size_t stringCount() const { return string_count_; }

  size_t floatArrayCount() const { return float_array_count_; }

  size_t integerArrayCount() const { return integer_array_count_; }

  size_t stringArrayCount() const { return string_array_count_; }

  size_t floatAlleleCount() const { return float_allele_count_; }

  size_t integerAlleleCount() const { return integer_allele_count_; }

  size_t stringAlleleCount() const { return string_allele_count_; }

  size_t booleanCount() const { return boolean_count_; }

  std::optional<InfoIndexMap> generateEvidenceIndex(const VCFInfoRecordMap &vcf_info_map);

  static InfoEvidenceType convertVCFType(const VCFInfoRecord &vcf_info_item);

  void incrementCount(InfoEvidenceType type);

private:

  size_t float_count_{0};
  size_t integer_count_{0};
  size_t string_count_{0};
  size_t float_array_count_{0};
  size_t integer_array_count_{0};
  size_t string_array_count_{0};
  size_t float_allele_count_{0};
  size_t integer_allele_count_{0};
  size_t string_allele_count_{0};
  size_t boolean_count_{0};

  constexpr static const char *INTEGER_ = "Integer";
  constexpr static const char *FLOAT_ = "Float";
  constexpr static const char *FLAG_ = "Flag";
  constexpr static const char *CHAR_STRING_ = "Character";
  constexpr static const char *STRING_ = "String";
  constexpr static const char *SCALAR_ = "1";
  constexpr static const char *AlTERNATIVE_ALLELE_ = "A";
  constexpr static const char *ALL_ALLELE_ = "R";
  constexpr static const char *ALL_GENOTYPES_ = "G";
  constexpr static const char *FLAG_SCALAR_ = "0";
  constexpr static const char *INDETERMINATE_COUNT_ = ".";

  void reset();

};


///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// An indexed map of InfoEvidenceIndex. There is only one of these held by all variants with INFO evidence fields.
struct InfoSubscribed {

  VCFInfoRecord vcf_record;
  InfoEvidenceType data_type;

};
using InfoSubscribedMap = std::map<std::string, InfoSubscribed>;

class InfoEvidenceHeader {

public:

  explicit InfoEvidenceHeader() {}

  InfoEvidenceHeader(const InfoEvidenceHeader &) = delete;

  ~InfoEvidenceHeader() = default;

  std::optional<const InfoEvidenceIndex> getIndex(const std::string &info) const;

  const InfoIndexMap &getMap() const { return info_index_map_; }

  // Note that this routine takes a shared_ptr to itself obtained from the info data factory. This is passed onto data objects.
  [[nodiscard]] bool
  setupEvidenceHeader(const InfoSubscribedMap &vcf_info_map, std::shared_ptr<const InfoEvidenceHeader> self_ptr);


private:

  InfoIndexMap info_index_map_;


};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// This is the per variant INFO data block.
// Generated from the parser data block by specifying the Allele index.
class EvidenceFactory; // Fwd.
class MultipleAlleleDataBlock;

class InfoDataBlock {

public:

  friend MultipleAlleleDataBlock;
  friend EvidenceFactory;

  InfoDataBlock(std::shared_ptr<InfoEvidenceHeader> info_evidence_header) : info_evidence_header_(
  std::move(info_evidence_header)) {}

  InfoDataBlock(const InfoEvidenceHeader &) = delete;

  ~InfoDataBlock() = default;

private:

  std::shared_ptr<InfoEvidenceHeader> info_evidence_header_; // The data header.

  // The stored data.
  std::vector<std::pair<bool, double>> float_data_;
  std::vector<std::pair<bool, long>> integer_data_;
  std::vector<std::pair<bool, std::string>> string_data_;
  std::vector<std::pair<bool, std::vector<double>>> float_array_data_;
  std::vector<std::pair<bool, std::vector<long>>> integer_array_data_;
  std::vector<std::pair<bool, std::vector<std::string>>> string_array_data_;


};


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// The evidence factory creates a common evidence lookup object for all variants (to optimize memory usage).
// The evidence factory also creates an evidence object for each variant.

// createVariantEvidence() either returns a single data block, InfoDataBlock for a single alternate allele or
// a MultipleAlleleDataBlock data block for a multiple alternative allele VCF record.
using InfoDataEvidence = std::optional<std::shared_ptr<InfoDataBlock>>;
class EvidenceFactory {

public:

  explicit EvidenceFactory(const EvidenceInfoSet& evidence_map)
  : evidence_map_(evidence_map),
    info_evidence_header_(std::make_shared<InfoEvidenceHeader>()) {}
  ~EvidenceFactory() = default;

  void availableInfoFields(const VCFInfoRecordMap& vcf_info_map);
  [[nodiscard]] const VCFInfoRecordMap& availableInfoFields() const { return all_available_map_; }
  [[nodiscard]] InfoDataEvidence createVariantEvidence(std::string&& info);

private:

  // The evidence fields specified in the runtime XML file.
  const EvidenceInfoSet evidence_map_;
  // available info fields parsed from the VCF header.
  InfoSubscribedMap active_info_map_;
  // All available info fields.
  VCFInfoRecordMap all_available_map_;
  // The info header block
  std::shared_ptr<InfoEvidenceHeader> info_evidence_header_;

  void parseSubscribed(std::string&& info);


};



} // namespace





#endif //KGL_VARIANT_FACTORY_VCF_EVIDENCE_H
