/*=============================================================================
Copyright (c) 2016 Paul W. Bible
Distributed under the Boost Software License, Version 1.0.
==============================================================================*/

#ifndef KGL_KOL_LIBRARY_H
#define KGL_KOL_LIBRARY

#include "kol_Accumulators.h"
#include "kol_AllowedRelationshipOboGoParser.h"
#include "kol_AllowedRelationshipXmlGoParser.h"
#include "kol_AllowedSetEvidencePolicy.h"
#include "kol_AllowedSetRelationshipPolicy.h"
#include "kol_AllPairsAverageSetSimilarity.h"
#include "kol_AllPairsMaxSetSimilarity.h"
#include "kol_AncestorMeanSharedInformation.h"
#include "kol_AnnotationData.h"
#include "kol_AnnotationParserFactory.h"
#include "kol_AnnotationParserInterface.h"
#include "kol_AsymmetricSimilarityCache.h"
#include "kol_BestMatchAverageSetSimilarity.h"
#include "kol_CoutoGraSMAdjustedSharedInformation.h"
#include "kol_CoutoGraSMSharedInformation.h"
#include "kol_DisallowedSetEvidencePolicy.h"
#include "kol_EnrichmentTools.h"
#include "kol_EntrezGene2GoAnnotationParser.h"
#include "kol_EvidencePolicyInterface.h"
#include "kol_ExclusivelyInheritedSharedInformation.h"
#include "kol_ExperimentalEvidencePolicy.h"
#include "kol_FrontierSharedInformation.h"
#include "kol_GentlemanSimUISetSimilarity.h"
#include "kol_GoaAnnotationParser.h"
#include "kol_GoEnums.h"
#include "kol_GoGraph.h"
#include "kol_GoParserFactory.h"
#include "kol_GoParserInterface.h"
#include "kol_JaccardSetSimilarity.h"
#include "kol_JiangConrathSimilarity.h"
#include "kol_LinSimilarity.h"
#include "kol_MazanduSimDICSetSimilarity.h"
#include "kol_MazanduSimUICSetSimilarity.h"
#include "kol_MgiAnnotationParser.h"
#include "kol_MICASharedInformation.h"
#include "kol_ModularJiangConrath.h"
#include "kol_ModularLin.h"
#include "kol_ModularResnik.h"
#include "kol_NCList.h"
#include "kol_PekarStaabSimilarity.h"
#include "kol_PesquitaSimGICSetSimilarity.h"
#include "kol_PrecomputedMatrixTermSimilarity.h"
#include "kol_RapidXmlGoParser.h"
#include "kol_RelationshipPolicyInterface.h"
#include "kol_RelevanceSimilarity.h"
#include "kol_ResnikSimilarity.h"
#include "kol_SetUtilities.h"
#include "kol_SharedInformationInterface.h"
#include "kol_SimpleRegion.h"
#include "kol_StandardOboGoParser.h"
#include "kol_StandardRelationshipPolicy.h"
#include "kol_StandardXmlGoParser.h"
#include "kol_TermDepthMap.h"
#include "kol_TermInformationContentMap.h"
#include "kol_TermProbabilityMap.h"
#include "kol_TermSetSimilarityInterface.h"
#include "kol_TermSimilarityCache.h"
#include "kol_TermSimilarityInterface.h"
#include "kol_TermSimilarityWriter.h"


#endif
