/*=============================================================================
Copyright (c) 2016 Paul W. Bible
Distributed under the Boost Software License, Version 1.0.
==============================================================================*/

#ifndef KGL_KOL_LIBRARY_H
#define KGL_KOL_LIBRARY

#include "kol_Accumulators.h"
#include "kol_AllowedRelationshipOboGoParser.h"
#include "kol_AllowedRelationshipXmlGoParser.h"
#include "kol_AllowedSetEvidencePolicy.h"
#include "kol_AllowedSetRelationshipPolicy.h"
#include "kol_SetSimilarityAllPairsAverage.h"
#include "kol_SetSimilarityAllPairsMax.h"
#include "kol_InformationAncestorMean.h"
#include "kol_AnnotationData.h"
#include "kol_AnnotationParserFactory.h"
#include "kol_AnnotationParserInterface.h"
#include "kol_SimilarityCacheAsymmetric.h"
#include "kol_SetSimilarityBestMatchAverage.h"
#include "kol_InformationCoutoGraSMAdjusted.h"
#include "kol_InformationCoutoGraSM.h"
#include "kol_DisallowedSetEvidencePolicy.h"
#include "kol_EnrichmentTools.h"
#include "kol_EntrezGene2GoAnnotationParser.h"
#include "kol_EvidencePolicyInterface.h"
#include "kol_InformationExclusiveInherited.h"
#include "kol_ExperimentalEvidencePolicy.h"
#include "kol_InformationFrontier.h"
#include "kol_SetSimilarityGentlemanSimUI.h"
#include "kol_GoaAnnotationParser.h"
#include "kol_GoEnums.h"
#include "kol_GoGraph.h"
#include "kol_GoParserFactory.h"
#include "kol_GoParserInterface.h"
#include "kol_SetSimilarityJaccard.h"
#include "kol_SetSimilarityMazanduSimDIC.h"
#include "kol_SetSimilarityMazanduSimUIC.h"
#include "kol_MgiAnnotationParser.h"
#include "kol_MICASharedInformation.h"
#include "kol_SimilarityJiangConrath.h"
#include "kol_SimilarityLin.h"
#include "kol_SimilarityRelevance.h"
#include "kol_SimilarityResnik.h"
#include "kol_SimilarityPekarStaab.h"
#include "kol_SetSimilarityPesquitaSimGIC.h"
#include "kol_SimilarityMatrix.h"
#include "kol_RapidXmlGoParser.h"
#include "kol_RelationshipPolicyInterface.h"
#include "kol_SetUtilities.h"
#include "kol_InformationInterface.h"
#include "kol_StandardOboGoParser.h"
#include "kol_StandardRelationshipPolicy.h"
#include "kol_StandardXmlGoParser.h"
#include "kol_TermDepthMap.h"
#include "kol_InformationContentDAG.h"
#include "kol_InformationContent.h"
#include "kol_SetSimilarityInterface.h"
#include "kol_SimilarityCache.h"
#include "kol_SimilarityInterface.h"
#include "kol_SimilarityWriter.h"


#endif
